### ISSUE TITLE
`bmap!` (and alikes) to use `ToOwned`

### ISSUE THREAD

**Issue by dpc** [rust-amplify/rust-amplify#140]
99% of the time users will want collections with owned values. Why wrap everything in `s!` etc. then? Possibly name `bmap_owned` to make the cloning explicit.

**Comment by dr-orlovsky** [comment]
Good point, but which value should be converted to the owned: key? value? both?

**Comment by dpc** [comment]
Both. My understanding is that `ToOwned` of an already owned value is a no-op anyway (just a move). So the problem with `ToOwned` is only that it makes easy to implicitly get an extra allocation, which is generally avoided in most standard APIs.
