### ISSUE TITLE
WASM support

### ISSUE THREAD

**Issue by cryptoquick** [rust-amplify/rust-amplify#143]
Moving this issue from https://github.com/LNP-BP/client_side_validation/issues/93

stens fails to compile to wasm32-unknown-unknown due to the dependency, amplify_syn.

I can add a WASM test to CI if it can help you resolve this issue, @dr-orlovsky.

**Comment by dr-orlovsky** [comment]
CI will be very helpful, thanks! I have not idea how to compile for WASM :)

**Comment by cryptoquick** [comment]
I can't seem to run my actions against this repo, but I did my best in #144 ... It should work, I think, but I can't know for sure till GH runs them.

**Comment by dr-orlovsky** [comment]
Ok, now I am able to compile to wasm target locally. The error preventing compilation comes not from the amplify crates, but from the upstream:

```
error[E0433]: failed to resolve: could not find `parse_quote_spanned` in `syn`
   --> /home/orlovsky/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-macro-support-0.2.83/src/parser.rs:110:38
```

It comes from `wasm-bindgen-macro-support` which seems to contain a bug. I tried to look into how it can be fixed, but not able to find...

**Comment by dr-orlovsky** [comment]
There was a similar issue reported years ago here and it was related to a rust compiler bug: https://github.com/rustwasm/wasm-bindgen/issues/1656

**Comment by dr-orlovsky** [comment]
Fixed: it just required to update minimal version of `syn`. Published to the crates.io

**Comment by cryptoquick** [comment]
Nice!

**Comment by dr-orlovsky** [comment]
Pls let me know if there any other issues preventing RGB on WASM
