### ISSUE TITLE
Error when sets the feature flag

### ISSUE THREAD

**Issue by crisdut** [rust-amplify/rust-amplify#209]
Hi @dr-orlovsky,

I found some issues in the flags api.

**Context**
I tried to establish a connection between `lnp-node` and `core-lightning` nodes, but `core-lightning` node sent some unknown flags and this caused panic in the peerd daemon.

```
 thread '<unnamed>' panicked at 'index out of bounds: the len is 1 but the index is 1', /rust-amplify/src/flags.rs:409:14
```

- When flag_no=0,  the method `mut_byte_at` return a wrong array position. 
- When flag_no=8, the methods `enlarge` and `bits_to_bytes` return a wrong length array.

**Comment by dr-orlovsky** [comment]
Fixed in https://github.com/rust-amplify/rust-amplify/pull/218

Backported to v3 and released as v3.14.1 in 62e3bcc7a17ae342f37cf1d6d5b21eac13c00216
